### ISSUE TITLE
下载后的验证码图片打不开

### ISSUE THREAD

**Issue by RicardoZZhong** [ghy20001114/zucc_xk_ZhengFang#9]
我只想爬取验证码然后手动输入，运行了你的爬取验证码的程序，下载下来的gif图片打开后什么也没有？能请教一下是怎么回事吗？

**Comment by zghyy** [comment]
你可以在OCR_CODE.py这里取消注释这段代码，这段代码是调用matplotlib.pyplot的imshow方法输出验证码图片的。同时也要导入对应的包
https://github.com/zghyy/zucc_xk_ZhengFang/blob/0167ea4109fa39c4214fa484f3ded1b1671b7d67/OCR_CODE.py#L7-L15

然后你需要在run方法中取消对show_code引用的注释，也就是下面代码的108行
https://github.com/zghyy/zucc_xk_ZhengFang/blob/0167ea4109fa39c4214fa484f3ded1b1671b7d67/OCR_CODE.py#L106-L113

这些都是在调试的时候使用的，里面有OCR自动输入验证码，不需要手动输入的

**Comment by zghyy** [comment]
还有关于下载下来的gif图片打开后什么也没有这个问题，这个是因为选课网上的图片是用的gif格式，然而他实际上是jpg格式。你可以通过重命名为xxx.jpg的方式看到图片的真实内容
